### ISSUE TITLE
nullspacex, rref don't work with non-rationals

### ISSUE THREAD

**Issue by zdroid** [scheinerman/LinearAlgebraX.jl#3]
An error is returned since `\\(Float64, Int64)` is not defined. Here's the source of the error:
https://github.com/scheinerman/LinearAlgebraX.jl/blob/master/src/rrefx.jl#L8
That conversion is done for every T, instead of int only.

**Comment by scheinerman** [comment]
Agreed, but it was never my intention that `rrefx` be used on a matrix with inexact (floating) numbers. The goal of `LinearAlgebraX` is exact results for exact matrices; no round off allowed.

**Comment by zdroid** [comment]
Yeah, I understand that. But other functions work with any type. Julia's syntax allows this at no additional costs.

Can you look at my proposal in #4? I want to use rrefx / nullspacex function in a project, and it'd be easier if it was just generic like this.
