### ISSUE TITLE
Faster determinant for `Mod` matrices via Smith normal form

### ISSUE THREAD

**Issue by ChenZhao44** [scheinerman/LinearAlgebraX.jl#9]
For a general matrix over $\mathbb{Z}\_d$, although Gaussian elimination might fail because elements in $\mathbb{Z}\_d$ could be noninvertible, we could still use Smith normal forms to compute the determinant. That is 
```math
S = UAV
```
where $A$ is a matrix over $\mathbb{Z}\_d$, and $U,V$ are invertible. Moreover, $S$ is diagonal such that $S_{i,i} \mid S_{i+1,i+1}$. 

For example, see https://cs.uwaterloo.ca/research/tr/1996/03/CS-96-03.pdf for more details.

**Comment by scheinerman** [comment]
Thanks. I doubt, though, that I'd have time to implement this.

**Comment by ChenZhao44** [comment]
Would you mind leave this issue open? I am trying to implement one for some applications where Smith normal form of matrices of `Mod` are needed. If yes, I am glad to submit a PR for that.

**Comment by scheinerman** [comment]
OK. It's re-opened.

**Comment by ChenZhao44** [comment]
Should be solved by #10
